// AUTO-GENERATED by scripts/gen-guides-index.mjs. Do not edit.
// Lightweight listing metadata only (no article bodies, sections, FAQs).
// Source of truth is src/lib/guides-data.ts. Regenerate via `bun run prebuild`
// or `bun run build`.

export type GuideIndexEntry = {
  slug: string;
  title: string;
  category: string;
  readTime: string;
  description: string;
  relatedCategory: string;
  relatedLabel: string;
};

export const guidesIndex: GuideIndexEntry[] = [
  {
    "slug": "budget-basics-50-30-20",
    "title": "Budget Basics: The 50/30/20 Rule Explained",
    "category": "Saving Money",
    "readTime": "6 min",
    "description": "A simple framework for allocating your income across needs, wants, and savings. The foundation of every strong financial plan.",
    "relatedCategory": "/financial-apps",
    "relatedLabel": "Budgeting Apps"
  },
  {
    "slug": "stop-subscription-drain",
    "title": "Subscriptions & Bills: Stop the Silent Drain",
    "category": "Saving Money",
    "readTime": "5 min",
    "description": "The average American wastes $924 per year on forgotten subscriptions. Here is exactly how to find and kill them.",
    "relatedCategory": "/financial-apps",
    "relatedLabel": "Bill Management Apps"
  },
  {
    "slug": "shopping-hacks",
    "title": "Shopping Hacks: Save on Groceries and Everyday Purchases",
    "category": "Saving Money",
    "readTime": "7 min",
    "description": "Practical tactics to cut grocery bills, everyday purchases, and online shopping costs by 15-30% without couponing.",
    "relatedCategory": "/financial-apps",
    "relatedLabel": "Cashback Apps"
  },
  {
    "slug": "travel-on-budget",
    "title": "Travel Tips: Vacation Without Breaking Your Budget",
    "category": "Saving Money",
    "readTime": "6 min",
    "description": "Book smarter, pack lighter, and cut travel costs 30-50%. Without sacrificing the quality of your trip.",
    "relatedCategory": "/financial-apps",
    "relatedLabel": "Travel Rewards"
  },
  {
    "slug": "big-purchase-guide",
    "title": "Big Purchases: What to Know Before You Buy",
    "category": "Saving Money",
    "readTime": "7 min",
    "description": "Cars, appliances, furniture, and electronics. How to research, time, and negotiate major purchases to save thousands.",
    "relatedCategory": "/bank-accounts",
    "relatedLabel": "Savings Accounts"
  },
  {
    "slug": "emergency-fund",
    "title": "Emergency Funds: How Much You Need and Where to Keep It",
    "category": "Saving Money",
    "readTime": "6 min",
    "description": "The right size, location, and timeline for building the safety net that protects every other financial goal.",
    "relatedCategory": "/bank-accounts",
    "relatedLabel": "High-Yield Savings"
  },
  {
    "slug": "savings-account-timeline",
    "title": "Savings Account Guide: Matching Accounts to Your Timeline",
    "category": "Saving Money",
    "readTime": "8 min",
    "description": "Not all savings are the same. Match each goal to the right account type for the best rate, access, and safety.",
    "relatedCategory": "/bank-accounts",
    "relatedLabel": "Bank Accounts"
  },
  {
    "slug": "investing-101",
    "title": "Investing 101: Stocks, Bonds, and Understanding Risk",
    "category": "Investing",
    "readTime": "9 min",
    "description": "A plain-English starting point for understanding what stocks, bonds, and funds actually are. And how risk really works.",
    "relatedCategory": "/investing",
    "relatedLabel": "Investing Platforms"
  },
  {
    "slug": "invest-smart-goals",
    "title": "How to Invest: The SMART Goal Framework",
    "category": "Investing",
    "readTime": "7 min",
    "description": "Turn vague 'I want to invest' ambitions into a concrete, measurable, time-bound investing plan.",
    "relatedCategory": "/investing",
    "relatedLabel": "Investing Platforms"
  },
  {
    "slug": "portfolio-building",
    "title": "Portfolio Building: Diversification and Asset Allocation",
    "category": "Investing",
    "readTime": "8 min",
    "description": "The single most important investment decision you will make. And how to get it right without overcomplicating it.",
    "relatedCategory": "/investing",
    "relatedLabel": "Investing Platforms"
  },
  {
    "slug": "portfolio-improvements",
    "title": "Portfolio Improvements: Rebalancing and Alternative Investments",
    "category": "Investing",
    "readTime": "7 min",
    "description": "How to keep a portfolio on target year after year. And when to consider REITs, commodities, or other alternatives.",
    "relatedCategory": "/investing",
    "relatedLabel": "Investing Platforms"
  },
  {
    "slug": "retirement-investing",
    "title": "Retirement Investing: The 20x Rule and Contribution Strategy",
    "category": "Investing",
    "readTime": "9 min",
    "description": "How much to save, which accounts to use, and the priority order that maximizes every retirement dollar.",
    "relatedCategory": "/investing",
    "relatedLabel": "Investing Platforms"
  },
  {
    "slug": "equities-trading",
    "title": "Equities Trading: Strategy, Orders, and Risk Management",
    "category": "Trading",
    "readTime": "10 min",
    "description": "If you are going to trade instead of invest, here is the framework that separates disciplined traders from gamblers.",
    "relatedCategory": "/investing",
    "relatedLabel": "Trading Platforms"
  },
  {
    "slug": "how-to-pick-high-yield-savings",
    "title": "How to Pick a High-Yield Savings Account",
    "category": "Saving Money",
    "readTime": "7 min",
    "description": "A practical checklist for choosing the right high-yield savings account. APY, fees, access, and FDIC insurance all matter.",
    "relatedCategory": "/financial-apps",
    "relatedLabel": "Banking Apps"
  },
  {
    "slug": "roth-vs-traditional-ira",
    "title": "Roth IRA vs. Traditional IRA: Which Is Right for You?",
    "category": "Retirement",
    "readTime": "8 min",
    "description": "A clear, side-by-side comparison to help you pick the right tax-advantaged retirement account for your situation.",
    "relatedCategory": "/investing",
    "relatedLabel": "Investing Platforms"
  },
  {
    "slug": "improve-credit-90-days",
    "title": "Improve Your Credit in 90 Days",
    "category": "Credit & Debt",
    "readTime": "9 min",
    "description": "A realistic, week-by-week action plan to boost your credit score by 30-80 points in three months. No gimmicks.",
    "relatedCategory": "/financial-apps",
    "relatedLabel": "Credit Monitoring Apps"
  },
  {
    "slug": "best-high-yield-savings-accounts-may-2026",
    "title": "Best High-Yield Savings Accounts for May 2026",
    "category": "Banking",
    "readTime": "12 min",
    "description": "Our top picks for high-yield savings accounts in May 2026, ranked by APY, fees, access, and tools. Rates up to 4.10% with no monthly fees.",
    "relatedCategory": "/bank-accounts",
    "relatedLabel": "Compare Bank Accounts"
  },
  {
    "slug": "best-budgeting-apps-2026",
    "title": "4 Best Budgeting Apps in 2026",
    "category": "Saving Money",
    "readTime": "10 min",
    "description": "Our top 4 budgeting apps for 2026, ranked by features, ease of use, automation, and price. Find the app that fits your style.",
    "relatedCategory": "/financial-apps",
    "relatedLabel": "Compare Budgeting Apps"
  },
  {
    "slug": "best-cash-advance-loan-apps-may-2026",
    "title": "7 Best Cash Advance & Loans Apps in May 2026",
    "category": "Saving Money",
    "readTime": "12 min",
    "description": "Our top 7 cash advance and small-loan apps for May 2026, ranked by speed, fees, limits, and credit-building. Find the right app for a paycheck gap.",
    "relatedCategory": "/financial-apps",
    "relatedLabel": "Compare Cash Advance Apps"
  },
  {
    "slug": "best-stock-picking-services-may-2026",
    "title": "Best 5 Stock Picking Services of May 2026",
    "category": "Investing",
    "readTime": "11 min",
    "description": "Our top 5 stock picking and research services for May 2026, ranked by pick quality, research depth, value, and usability.",
    "relatedCategory": "/investing",
    "relatedLabel": "Compare Investing Tools"
  },
  {
    "slug": "best-bank-bonuses-this-month",
    "title": "Best Bank Bonuses This Month",
    "category": "Saving Money",
    "readTime": "8 min",
    "description": "The highest-paying checking and savings account bonuses available right now. Vetted, ranked, and broken down by deposit requirements and difficulty.",
    "relatedCategory": "/bank-accounts",
    "relatedLabel": "Bank Accounts"
  },
  {
    "slug": "5-best-investing-apps-may-2026",
    "title": "5 Best Investing Apps for May 2026",
    "category": "Investing",
    "readTime": "10 min",
    "description": "Our updated ranking of the top 5 investing apps for May 2026. Commission-free trading, fractional shares, and retirement accounts.",
    "relatedCategory": "/investing",
    "relatedLabel": "Investing"
  },
  {
    "slug": "6-best-crypto-apps-2026",
    "title": "6 Best Crypto Apps for Trading & Crypto Wallets",
    "category": "Investing",
    "readTime": "11 min",
    "description": "The top 6 crypto exchanges and wallets for U.S. users in 2026. Ranked by fees, security, asset selection, staking yields, and Web3 features.",
    "relatedCategory": "/financial-apps",
    "relatedLabel": "Crypto Apps"
  },
  {
    "slug": "hysa-vs-money-market-vs-cds",
    "title": "HYSA vs Money Market vs CDs: Where to Park Your Cash",
    "category": "Saving Money",
    "readTime": "8 min",
    "description": "High-yield savings, money market accounts, and CDs all pay strong interest in 2026. But they serve very different jobs. Here is how to choose.",
    "relatedCategory": "/bank-accounts",
    "relatedLabel": "Compare Bank Accounts"
  },
  {
    "slug": "index-funds-vs-etfs-vs-mutual-funds",
    "title": "Index Funds vs ETFs vs Mutual Funds Explained",
    "category": "Investing",
    "readTime": "9 min",
    "description": "Index funds, ETFs, and mutual funds are not interchangeable. Here is how they differ and which one fits your investing goals.",
    "relatedCategory": "/investing",
    "relatedLabel": "Compare Brokerages"
  },
  {
    "slug": "how-to-invest-first-10k",
    "title": "How to Invest: Your First $100 to Your First $10,000",
    "category": "Investing",
    "readTime": "12 min",
    "description": "A complete walkthrough from opening a brokerage to placing your first ETF trade, setting up auto-contributions, and surviving year one without rookie mistakes.",
    "relatedCategory": "/investing",
    "relatedLabel": "Investing Apps"
  },
  {
    "slug": "taxes-and-inheritance-for-investors",
    "title": "Taxes and Inheritance for Investors",
    "category": "Investing",
    "readTime": "14 min",
    "description": "Capital gains, tax-loss harvesting, step-up in basis, inherited IRAs under the SECURE Act, and the estate-planning mechanics every investor eventually needs.",
    "relatedCategory": "/investing",
    "relatedLabel": "Investing Apps"
  },
  {
    "slug": "options-101",
    "title": "Options 101: Calls, Puts, and How They Actually Work",
    "category": "Trading",
    "readTime": "11 min",
    "description": "A technical but accessible intro to options. Contracts, strikes, expiration, intrinsic vs extrinsic value, and payoff diagram math.",
    "relatedCategory": "/investing",
    "relatedLabel": "Trading Platforms"
  },
  {
    "slug": "the-greeks-explained",
    "title": "The Greeks Explained: Delta, Gamma, Theta, Vega, Rho",
    "category": "Trading",
    "readTime": "10 min",
    "description": "Every options trader has to understand the Greeks. Here is what each one measures, how they interact, and examples that make the numbers click.",
    "relatedCategory": "/investing",
    "relatedLabel": "Trading Platforms"
  },
  {
    "slug": "options-strategies",
    "title": "Options Strategies: Covered Calls, CSPs, Verticals, and Iron Condors",
    "category": "Trading",
    "readTime": "13 min",
    "description": "The four defined-risk options strategies that cover 90% of what retail traders actually need. With break-even math, max profit/loss, and when each one shines.",
    "relatedCategory": "/investing",
    "relatedLabel": "Trading Platforms"
  }
];
