/*
  # Seed partners and offers

  Populates the partners and offers tables from the initial product catalog in
  src/data/products.ts. Partner slugs are the subdomain label; offer slugs are
  the product-prefixed URL path segment.

  1. Inserts
    - Partners: sofi, ally, chase, chime, amex, axos, etrade, upgrade,
      marcus, barclays, citbank, bread, lendingclub, forbright, wellsfargo,
      bofa, citi, usbank, truist, discover, capitalone, nbkc, pnc,
      fidelity, robinhood, vanguard, webull, interactivebrokers, schwab,
      moomoo, m1finance, betterment, acorns, wealthfront, coinbase, kraken,
      gemini, cryptocom, uphold, okx, kalshi, polymarket, ynab, monarch,
      rocketmoney, empower, earnin, dave, albert, brigit, possiblefinance,
      tilt, creditkarma, experian, current, varo, cashapp, perpay, motleyfool,
      seekingalpha, tipranks, tradingview, cnbc, stockanalysis
    - Offers: one per product entry, slug = kebab product name

  2. Idempotency
    - Uses ON CONFLICT DO NOTHING on both tables so re-running this migration
      won't duplicate or overwrite hand-edited rows.
*/

INSERT INTO partners (slug, name, default_destination_url) VALUES
  ('sofi', 'SoFi', 'https://www.sofi.com/'),
  ('ally', 'Ally', 'https://www.ally.com/'),
  ('chase', 'Chase', 'https://www.chase.com/'),
  ('chime', 'Chime', 'https://www.chime.com/'),
  ('amex', 'American Express', 'https://www.americanexpress.com/'),
  ('axos', 'Axos Bank', 'https://www.axosbank.com/'),
  ('etrade', 'E*TRADE', 'https://us.etrade.com/'),
  ('upgrade', 'Upgrade', 'https://www.upgrade.com/'),
  ('marcus', 'Marcus by Goldman Sachs', 'https://www.marcus.com/'),
  ('barclays', 'Barclays', 'https://banking.us.barclays/'),
  ('citbank', 'CIT Bank', 'https://www.cit.com/'),
  ('bread', 'Bread Savings', 'https://www.breadfinancial.com/'),
  ('lendingclub', 'LendingClub', 'https://www.lendingclub.com/'),
  ('forbright', 'Forbright Bank', 'https://www.forbrightbank.com/'),
  ('wellsfargo', 'Wells Fargo', 'https://www.wellsfargo.com/'),
  ('bofa', 'Bank of America', 'https://www.bankofamerica.com/'),
  ('citi', 'Citibank', 'https://www.citi.com/'),
  ('usbank', 'U.S. Bank', 'https://www.usbank.com/'),
  ('truist', 'Truist', 'https://www.truist.com/'),
  ('discover', 'Discover', 'https://www.discover.com/'),
  ('capitalone', 'Capital One', 'https://www.capitalone.com/'),
  ('nbkc', 'NBKC Bank', 'https://www.nbkc.com/'),
  ('pnc', 'PNC Bank', 'https://www.pnc.com/'),
  ('fidelity', 'Fidelity', 'https://www.fidelity.com/'),
  ('robinhood', 'Robinhood', 'https://robinhood.com/'),
  ('vanguard', 'Vanguard', 'https://investor.vanguard.com/'),
  ('webull', 'Webull', 'https://www.webull.com/'),
  ('interactivebrokers', 'Interactive Brokers', 'https://www.interactivebrokers.com/'),
  ('schwab', 'Charles Schwab', 'https://www.schwab.com/'),
  ('moomoo', 'MooMoo', 'https://www.moomoo.com/us'),
  ('m1finance', 'M1 Finance', 'https://m1.com/'),
  ('betterment', 'Betterment', 'https://www.betterment.com/'),
  ('acorns', 'Acorns', 'https://www.acorns.com/'),
  ('wealthfront', 'Wealthfront', 'https://www.wealthfront.com/'),
  ('coinbase', 'Coinbase', 'https://www.coinbase.com/'),
  ('kraken', 'Kraken', 'https://www.kraken.com/'),
  ('gemini', 'Gemini', 'https://www.gemini.com/'),
  ('cryptocom', 'Crypto.com', 'https://crypto.com/us'),
  ('uphold', 'Uphold', 'https://uphold.com/en-us'),
  ('okx', 'OKX', 'https://www.okx.com/'),
  ('kalshi', 'Kalshi', 'https://kalshi.com/'),
  ('polymarket', 'Polymarket', 'https://polymarket.com/'),
  ('ynab', 'YNAB', 'https://www.ynab.com/'),
  ('monarch', 'Monarch Money', 'https://www.monarch.com/'),
  ('rocketmoney', 'Rocket Money', 'https://www.rocketmoney.com/'),
  ('empower', 'Empower', 'https://www.empower.com/'),
  ('earnin', 'EarnIn', 'https://www.earnin.com/'),
  ('dave', 'Dave', 'https://dave.com/'),
  ('albert', 'Albert', 'https://albert.com/'),
  ('brigit', 'Brigit', 'https://www.hellobrigit.com/'),
  ('possiblefinance', 'Possible Finance', 'https://www.possiblefinance.com/'),
  ('tilt', 'Tilt', 'https://www.tilt.com/'),
  ('creditkarma', 'Credit Karma', 'https://www.creditkarma.com/'),
  ('experian', 'Experian', 'https://www.experian.com/'),
  ('current', 'Current', 'https://current.com/'),
  ('varo', 'Varo', 'https://www.varomoney.com/'),
  ('cashapp', 'Cash App', 'https://cash.app/'),
  ('perpay', 'PerPay', 'https://perpay.com/'),
  ('motleyfool', 'The Motley Fool', 'https://www.fool.com/'),
  ('seekingalpha', 'Seeking Alpha', 'https://seekingalpha.com/'),
  ('tipranks', 'TipRanks', 'https://www.tipranks.com/'),
  ('tradingview', 'TradingView', 'https://www.tradingview.com/'),
  ('cnbc', 'CNBC Pro', 'https://www.cnbc.com/pro/'),
  ('stockanalysis', 'Stock Analysis Pro', 'https://stockanalysis.com/')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO offers (partner_id, slug, product_type, name, destination_url, campaign)
SELECT p.id, v.offer_slug, v.product_type, v.name, v.destination_url, v.offer_slug
FROM partners p
JOIN (VALUES
  ('sofi', 'sofi-checking-savings', 'hysa', 'SoFi Checking & Savings', 'https://www.sofi.com/banking/'),
  ('sofi', 'sofi-checking', 'checking', 'SoFi Checking', 'https://www.sofi.com/banking/checking-account/'),
  ('sofi', 'sofi-invest', 'brokerage', 'SoFi Invest', 'https://www.sofi.com/invest/'),
  ('ally', 'ally-online-savings', 'hysa', 'Ally Online Savings', 'https://www.ally.com/bank/online-savings-account/'),
  ('ally', 'ally-interest-checking', 'checking', 'Ally Interest Checking', 'https://www.ally.com/bank/interest-checking-account/'),
  ('chase', 'chase-savings', 'hysa', 'Chase Savings', 'https://www.chase.com/personal/savings/savings-account'),
  ('chase', 'chase-total-checking', 'checking', 'Chase Total Checking', 'https://www.chase.com/personal/checking/total-checking'),
  ('chime', 'chime-high-yield-savings', 'hysa', 'Chime High Yield Savings', 'https://www.chime.com/savings-account/'),
  ('chime', 'chime-checking', 'checking', 'Chime Checking', 'https://www.chime.com/checking-account/'),
  ('chime', 'chime-mypay', 'cash-advance', 'Chime MyPay', 'https://www.chime.com/mypay/'),
  ('amex', 'amex-high-yield-savings', 'hysa', 'American Express High Yield Savings', 'https://www.americanexpress.com/en-us/banking/online-savings/high-yield-savings-account/'),
  ('amex', 'amex-rewards-checking', 'checking', 'American Express Rewards Checking', 'https://www.americanexpress.com/en-us/banking/checking-account/'),
  ('axos', 'axos-one-savings', 'hysa', 'Axos ONE Savings', 'https://www.axosbank.com/personal/savings/savings-account'),
  ('axos', 'axos-rewards-checking', 'checking', 'Axos Rewards Checking', 'https://www.axosbank.com/personal/checking/rewards-checking'),
  ('etrade', 'etrade-max-rate-checking', 'checking', 'E*TRADE Max-Rate Checking', 'https://us.etrade.com/bank/max-rate-checking'),
  ('etrade', 'etrade-invest', 'brokerage', 'E*TRADE Invest', 'https://us.etrade.com/bank'),
  ('upgrade', 'upgrade-rewards-checking', 'checking', 'Upgrade Rewards Checking Plus', 'https://www.upgrade.com/rewards-checking/'),
  ('upgrade', 'upgrade-credit', 'credit-loans', 'Upgrade Credit & Loans', 'https://www.upgrade.com/'),
  ('marcus', 'marcus-high-yield-savings', 'hysa', 'Marcus Online Savings', 'https://www.marcus.com/us/en/savings/high-yield-savings'),
  ('barclays', 'barclays-online-savings', 'hysa', 'Barclays Online Savings', 'https://banking.us.barclays/'),
  ('citbank', 'cit-platinum-savings', 'hysa', 'CIT Bank Platinum Savings', 'https://www.cit.com/bank/savings/platinum-savings'),
  ('bread', 'bread-savings-high-yield', 'hysa', 'Bread Savings High-Yield Savings', 'https://www.breadfinancial.com/en/bread-savings.html'),
  ('lendingclub', 'lendingclub-levelup-savings', 'hysa', 'LendingClub LevelUp Savings', 'https://www.lendingclub.com/personal-banking/savings/high-yield-savings'),
  ('forbright', 'forbright-growth-savings', 'hysa', 'Forbright Growth Savings', 'https://www.forbrightbank.com/personal-banking/growth-savings/'),
  ('wellsfargo', 'wellsfargo-platinum-savings', 'hysa', 'Wells Fargo Platinum Savings', 'https://www.wellsfargo.com/savings-cds/platinum/'),
  ('bofa', 'bofa-advantage-savings', 'hysa', 'Bank of America Advantage Savings', 'https://www.bankofamerica.com/deposits/savings/savings-accounts/'),
  ('citi', 'citi-savings', 'hysa', 'Citibank Savings', 'https://www.citi.com/banking/savings-accounts'),
  ('usbank', 'usbank-standard-savings', 'hysa', 'U.S. Bank Standard Savings', 'https://www.usbank.com/bank-accounts/savings-accounts.html'),
  ('truist', 'truist-one-savings', 'hysa', 'Truist One Savings', 'https://www.truist.com/savings/truist-one-savings'),
  ('discover', 'discover-cashback-debit', 'checking', 'Discover Cashback Debit', 'https://www.discover.com/online-banking/?src=dfs117-checking-account'),
  ('capitalone', 'capitalone-360-checking', 'checking', 'Capital One 360 Checking', 'https://www.capitalone.com/bank/checking-accounts/online-checking-account/'),
  ('nbkc', 'nbkc-everything-account', 'checking', 'NBKC Everything Account', 'https://www.nbkc.com/personal/everything-account'),
  ('pnc', 'pnc-virtual-wallet', 'checking', 'PNC Virtual Wallet', 'https://www.pnc.com/en/personal-banking/banking/checking.html'),
  ('fidelity', 'fidelity-investments', 'brokerage', 'Fidelity Investments', 'https://www.fidelity.com/'),
  ('robinhood', 'robinhood-invest', 'brokerage', 'Robinhood', 'https://robinhood.com/us/en/'),
  ('vanguard', 'vanguard-invest', 'brokerage', 'Vanguard', 'https://investor.vanguard.com/'),
  ('webull', 'webull-invest', 'brokerage', 'Webull', 'https://www.webull.com/'),
  ('interactivebrokers', 'interactivebrokers-invest', 'brokerage', 'Interactive Brokers', 'https://www.interactivebrokers.com/'),
  ('schwab', 'schwab-invest', 'brokerage', 'Charles Schwab', 'https://www.schwab.com/'),
  ('moomoo', 'moomoo-invest', 'brokerage', 'MooMoo', 'https://www.moomoo.com/us'),
  ('m1finance', 'm1-finance-invest', 'robo', 'M1 Finance', 'https://m1.com/'),
  ('betterment', 'betterment-robo', 'robo', 'Betterment', 'https://www.betterment.com/'),
  ('acorns', 'acorns-invest', 'robo', 'Acorns', 'https://www.acorns.com/'),
  ('wealthfront', 'wealthfront-robo', 'robo', 'Wealthfront', 'https://www.wealthfront.com/'),
  ('coinbase', 'coinbase-exchange', 'crypto', 'Coinbase', 'https://www.coinbase.com/'),
  ('kraken', 'kraken-exchange', 'crypto', 'Kraken', 'https://www.kraken.com/'),
  ('gemini', 'gemini-exchange', 'crypto', 'Gemini', 'https://www.gemini.com/'),
  ('cryptocom', 'cryptocom-exchange', 'crypto', 'Crypto.com', 'https://crypto.com/us'),
  ('uphold', 'uphold-exchange', 'crypto', 'Uphold', 'https://uphold.com/en-us'),
  ('okx', 'okx-exchange', 'crypto', 'OKX', 'https://www.okx.com/'),
  ('kalshi', 'kalshi-prediction-markets', 'prediction', 'Kalshi', 'https://kalshi.com/'),
  ('polymarket', 'polymarket-prediction-markets', 'prediction', 'Polymarket', 'https://polymarket.com/'),
  ('ynab', 'ynab-budgeting', 'budgeting', 'YNAB', 'https://www.ynab.com/'),
  ('monarch', 'monarch-money-budgeting', 'budgeting', 'Monarch Money', 'https://www.monarch.com/'),
  ('rocketmoney', 'rocket-money-budgeting', 'budgeting', 'Rocket Money', 'https://www.rocketmoney.com/'),
  ('empower', 'empower-personal-dashboard', 'budgeting', 'Empower Personal Dashboard', 'https://www.empower.com/personal-dashboard'),
  ('earnin', 'earnin-cash-advance', 'cash-advance', 'EarnIn', 'https://www.earnin.com/'),
  ('dave', 'dave-cash-advance', 'cash-advance', 'Dave', 'https://dave.com/'),
  ('albert', 'albert-cash-advance', 'cash-advance', 'Albert', 'https://albert.com/'),
  ('brigit', 'brigit-cash-advance', 'cash-advance', 'Brigit', 'https://www.hellobrigit.com/'),
  ('possiblefinance', 'possible-finance-cash-advance', 'cash-advance', 'Possible Finance', 'https://www.possiblefinance.com/'),
  ('tilt', 'tilt-cash-advance', 'cash-advance', 'Tilt', 'https://www.tilt.com/'),
  ('creditkarma', 'credit-karma-credit-score', 'credit-score', 'Credit Karma', 'https://www.creditkarma.com/'),
  ('experian', 'experian-credit-score', 'credit-score', 'Experian', 'https://www.experian.com/'),
  ('current', 'current-neobank', 'neobank', 'Current', 'https://current.com/'),
  ('varo', 'varo-neobank', 'neobank', 'Varo', 'https://www.varomoney.com/bank-account/'),
  ('cashapp', 'cash-app-neobank', 'neobank', 'Cash App', 'https://cash.app/'),
  ('perpay', 'perpay-credit', 'credit-loans', 'PerPay', 'https://perpay.com/'),
  ('motleyfool', 'motley-fool-stock-advisor', 'research', 'Motley Fool Stock Advisor', 'https://www.fool.com/services/stock-advisor/'),
  ('seekingalpha', 'seeking-alpha-research', 'research', 'Seeking Alpha', 'https://seekingalpha.com/'),
  ('tipranks', 'tipranks-research', 'research', 'TipRanks', 'https://www.tipranks.com/'),
  ('tradingview', 'tradingview-research', 'research', 'TradingView', 'https://www.tradingview.com/'),
  ('cnbc', 'cnbc-pro-research', 'research', 'CNBC Pro', 'https://www.cnbc.com/pro/'),
  ('stockanalysis', 'stock-analysis-pro-research', 'research', 'Stock Analysis Pro', 'https://stockanalysis.com/pro/')
) AS v(partner_slug, offer_slug, product_type, name, destination_url)
  ON v.partner_slug = p.slug
ON CONFLICT (partner_id, slug) DO NOTHING;
